version: 1
formatters:
    simple:
        format: '%(asctime)s [%(levelname)5s] %(name)8s %(threadName)8s: %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: crawler.log
        maxBytes: 30485760
        backupCount: 20
        encoding: utf8
loggers:
    Crawler:
        level: INFO
        handlers: [file]
        propagate: no
root:
    level: DEBUG
    handlers: [console, file]