version: 1
formatters:
    simple:
        format: '%(asctime)s [%(levelname)5s] %(name)8s %(threadName)8s: %(message)s'
    terminal:
        format: '%(log_color)s%(message)s'
        (): __main__.ColoredFormatter
        log_colors:
            DEBUG: purple
            INFO: white
            WARNING: red
            ERROR: purple
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: terminal
        stream: ext://sys.stdout
    file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: crawler.log
        maxBytes: 30485760
        backupCount: 20
        encoding: utf8
loggers:
    Crawler:
        level: DEBUG
        handlers: [file]
        propagate: no
    neobolt:
        level: WARN
root:
    level: DEBUG
    handlers: [console, file]